# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'VkStyle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '5.0.2'

  pod 'RealmSwift'
  pod 'PromiseKit'

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
    
  # Pods for VkStyle

end
